import type { IdPermiso, PermisoCatalogo } from './tiposRolesPermisos';

export const CATALOGO_PERMISOS: PermisoCatalogo[] = [
  {
    id: 'ventas.comprobantes.ver',
    nombre: 'Ver comprobantes',
    descripcion: 'Acceder a la lista y detalle de comprobantes.',
    modulo: 'ventas',
    rutas: ['/comprobantes'],
  },
  {
    id: 'ventas.comprobantes.emitir',
    nombre: 'Emitir comprobantes',
    descripcion: 'Crear comprobantes desde emision o POS.',
    modulo: 'ventas',
    rutas: ['/comprobantes/emision', '/comprobantes/nuevo', '/comprobantes/pos'],
  },
  {
    id: 'ventas.comprobantes.borradores.ver',
    nombre: 'Ver borradores de comprobantes',
    descripcion: 'Acceder a la lista de borradores.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.comprobantes.borradores.duplicar',
    nombre: 'Duplicar borradores',
    descripcion: 'Duplicar un borrador existente.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.comprobantes.borradores.eliminar',
    nombre: 'Eliminar borradores',
    descripcion: 'Eliminar borradores de comprobantes.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.pos.ver',
    nombre: 'Ver punto de venta',
    descripcion: 'Acceder a las pantallas de POS.',
    modulo: 'ventas',
    rutas: ['/punto-venta', '/punto-venta/dashboard', '/punto-venta/nueva-venta'],
  },
  {
    id: 'ventas.pos.vender',
    nombre: 'Registrar ventas POS',
    descripcion: 'Crear ventas y emitir comprobantes desde POS.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.pos.imprimir',
    nombre: 'Imprimir comprobantes POS',
    descripcion: 'Imprimir comprobantes desde POS.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.documentos.crear',
    nombre: 'Crear documentos de negociacion',
    descripcion: 'Crear cotizaciones o notas de venta.',
    modulo: 'ventas',
    rutas: ['/documentos-negociacion', '/documentos/cotizacion/nueva', '/documentos/nota-venta/nueva'],
  },
  {
    id: 'ventas.documentos.editar',
    nombre: 'Editar documentos de negociacion',
    descripcion: 'Editar documentos de negociacion existentes.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.documentos.eliminar',
    nombre: 'Eliminar documentos de negociacion',
    descripcion: 'Eliminar documentos de negociacion.',
    modulo: 'ventas',
  },
  {
    id: 'clientes.ver',
    nombre: 'Ver clientes',
    descripcion: 'Acceder al listado y detalle de clientes.',
    modulo: 'clientes',
    rutas: ['/clientes', '/clientes/:clienteId/:clienteName/historial'],
  },
  {
    id: 'clientes.crear',
    nombre: 'Crear clientes',
    descripcion: 'Registrar nuevos clientes.',
    modulo: 'clientes',
  },
  {
    id: 'clientes.editar',
    nombre: 'Editar clientes',
    descripcion: 'Editar informacion de clientes.',
    modulo: 'clientes',
  },
  {
    id: 'clientes.eliminar',
    nombre: 'Eliminar clientes',
    descripcion: 'Eliminar clientes.',
    modulo: 'clientes',
  },
  {
    id: 'clientes.importar',
    nombre: 'Importar clientes',
    descripcion: 'Importar clientes en lote.',
    modulo: 'clientes',
    rutas: ['/importar-clientes'],
  },
  {
    id: 'cobranzas.ver',
    nombre: 'Ver cobranzas',
    descripcion: 'Acceder al modulo de cobranzas.',
    modulo: 'cobranzas',
    rutas: ['/cobranzas'],
  },
  {
    id: 'cobranzas.registrar',
    nombre: 'Registrar cobranzas',
    descripcion: 'Registrar pagos y cobranzas.',
    modulo: 'cobranzas',
  },
  {
    id: 'caja.ver',
    nombre: 'Ver caja',
    descripcion: 'Acceder al modulo de caja.',
    modulo: 'caja',
    rutas: ['/control-caja', '/caja/sesiones'],
  },
  {
    id: 'caja.abrir',
    nombre: 'Abrir caja',
    descripcion: 'Registrar apertura de caja.',
    modulo: 'caja',
  },
  {
    id: 'caja.cerrar',
    nombre: 'Cerrar caja',
    descripcion: 'Registrar cierre de caja.',
    modulo: 'caja',
  },
  {
    id: 'caja.movimientos.registrar',
    nombre: 'Registrar movimientos de caja',
    descripcion: 'Registrar ingresos y egresos de caja.',
    modulo: 'caja',
  },
  {
    id: 'inventario.ver',
    nombre: 'Ver inventario',
    descripcion: 'Acceder al modulo de inventario.',
    modulo: 'inventario',
    rutas: ['/inventario'],
  },
  {
    id: 'inventario.ajustar',
    nombre: 'Ajustar inventario',
    descripcion: 'Registrar ajustes de stock.',
    modulo: 'inventario',
  },
  {
    id: 'inventario.transferir',
    nombre: 'Transferir inventario',
    descripcion: 'Registrar transferencias de stock.',
    modulo: 'inventario',
  },
  {
    id: 'inventario.actualizacion_masiva',
    nombre: 'Actualizacion masiva de inventario',
    descripcion: 'Aplicar actualizaciones masivas de stock.',
    modulo: 'inventario',
  },
  {
    id: 'catalogo.ver',
    nombre: 'Ver catalogo',
    descripcion: 'Acceder al catalogo de productos.',
    modulo: 'catalogo',
    rutas: ['/catalogo'],
  },
  {
    id: 'catalogo.crear',
    nombre: 'Crear productos',
    descripcion: 'Registrar productos en el catalogo.',
    modulo: 'catalogo',
  },
  {
    id: 'catalogo.editar',
    nombre: 'Editar productos',
    descripcion: 'Editar productos del catalogo.',
    modulo: 'catalogo',
  },
  {
    id: 'catalogo.eliminar',
    nombre: 'Eliminar productos',
    descripcion: 'Eliminar productos del catalogo.',
    modulo: 'catalogo',
  },
  {
    id: 'precios.ver',
    nombre: 'Ver precios',
    descripcion: 'Acceder a la lista de precios.',
    modulo: 'precios',
    rutas: ['/lista-precios'],
  },
  {
    id: 'precios.editar',
    nombre: 'Editar precios',
    descripcion: 'Editar listas o reglas de precios.',
    modulo: 'precios',
  },
  {
    id: 'indicadores.ver',
    nombre: 'Ver indicadores',
    descripcion: 'Acceder a indicadores del negocio.',
    modulo: 'indicadores',
    rutas: ['/indicadores'],
  },
  {
    id: 'config.panel.ver',
    nombre: 'Ver panel de configuracion',
    descripcion: 'Acceder al panel principal de configuracion.',
    modulo: 'configuracion',
    rutas: ['/configuracion'],
  },
  {
    id: 'config.empresa.ver',
    nombre: 'Ver configuracion de empresa',
    descripcion: 'Acceder a los datos de empresa.',
    modulo: 'configuracion',
    rutas: ['/configuracion/empresa'],
  },
  {
    id: 'config.empresa.editar',
    nombre: 'Editar configuracion de empresa',
    descripcion: 'Editar los datos de empresa.',
    modulo: 'configuracion',
  },
  {
    id: 'config.establecimientos.gestionar',
    nombre: 'Gestionar establecimientos',
    descripcion: 'Crear, editar o eliminar establecimientos.',
    modulo: 'configuracion',
    rutas: ['/configuracion/establecimientos'],
  },
  {
    id: 'config.almacenes.gestionar',
    nombre: 'Gestionar almacenes',
    descripcion: 'Crear, editar o eliminar almacenes.',
    modulo: 'configuracion',
    rutas: ['/configuracion/almacenes'],
  },
  {
    id: 'config.series.gestionar',
    nombre: 'Gestionar series',
    descripcion: 'Crear, editar o eliminar series.',
    modulo: 'configuracion',
    rutas: ['/configuracion/series'],
  },
  {
    id: 'config.series.correlativo.ajustar',
    nombre: 'Ajustar correlativo de series',
    descripcion: 'Ajustar el correlativo de series.',
    modulo: 'configuracion',
  },
  {
    id: 'config.negocio.gestionar',
    nombre: 'Gestionar configuracion de negocio',
    descripcion: 'Actualizar medios de pago, impuestos, unidades y preferencias.',
    modulo: 'configuracion',
    rutas: ['/configuracion/negocio'],
  },
  {
    id: 'config.diseno_comprobante.gestionar',
    nombre: 'Gestionar diseno de comprobantes',
    descripcion: 'Configurar el diseno de comprobantes.',
    modulo: 'configuracion',
    rutas: ['/configuracion/diseno'],
  },
  {
    id: 'config.diseno_comprobante.importar_exportar',
    nombre: 'Importar y exportar diseno de comprobantes',
    descripcion: 'Importar o exportar configuraciones de diseno.',
    modulo: 'configuracion',
  },
  {
    id: 'config.cajas.gestionar',
    nombre: 'Gestionar cajas',
    descripcion: 'Crear, editar o eliminar cajas.',
    modulo: 'configuracion',
    rutas: ['/configuracion/cajas', '/configuracion/cajas/new', '/configuracion/cajas/:id'],
  },
  {
    id: 'config.usuarios.gestionar',
    nombre: 'Gestionar usuarios',
    descripcion: 'Crear, editar o eliminar usuarios.',
    modulo: 'configuracion',
    rutas: ['/configuracion/usuarios'],
  },
  {
    id: 'config.usuarios.accesos.gestionar',
    nombre: 'Gestionar accesos de usuarios',
    descripcion: 'Gestionar asignaciones y roles de usuarios.',
    modulo: 'configuracion',
  },
  {
    id: 'config.usuarios.reset_password',
    nombre: 'Restablecer credenciales',
    descripcion: 'Restablecer credenciales sin exponer contrasenas.',
    modulo: 'configuracion',
  },
  {
    id: 'notificaciones.ver',
    nombre: 'Ver notificaciones',
    descripcion: 'Acceder al centro de notificaciones.',
    modulo: 'notificaciones',
    rutas: ['/notificaciones'],
  },
];

export const MAPA_PERMISOS_POR_ID: Record<IdPermiso, PermisoCatalogo> =
  CATALOGO_PERMISOS.reduce<Record<IdPermiso, PermisoCatalogo>>((acc, permiso) => {
    acc[permiso.id] = permiso;
    return acc;
  }, {});
