export const EVENTOS_POSTHOG_KPI = {
  VENTA_COMPLETADA: 'venta_completada',
  PRODUCTO_CREADO_EXITOSO: 'producto_creado_exitoso',
  CLIENTE_CREADO_EXITOSO: 'cliente_creado_exitoso',
  IMPORTACION_COMPLETADA: 'importacion_completada',
  REGISTRO_USUARIO_COMPLETADO: 'registro_usuario_completado'
} as const

export type EventoPosthogKpi = (typeof EVENTOS_POSTHOG_KPI)[keyof typeof EVENTOS_POSTHOG_KPI]

export const EVENTOS_POSTHOG_KPI_LISTA = [
  EVENTOS_POSTHOG_KPI.VENTA_COMPLETADA,
  EVENTOS_POSTHOG_KPI.PRODUCTO_CREADO_EXITOSO,
  EVENTOS_POSTHOG_KPI.CLIENTE_CREADO_EXITOSO,
  EVENTOS_POSTHOG_KPI.IMPORTACION_COMPLETADA,
  EVENTOS_POSTHOG_KPI.REGISTRO_USUARIO_COMPLETADO
] as const
