import { ANALYTICS_EVENTS } from '@facturafacil/analytics-events'

export const EVENTOS_POSTHOG_KPI = {
  VENTA_COMPLETADA: ANALYTICS_EVENTS.VENTA_COMPLETADA,
  PRODUCTO_CREADO_EXITOSO: ANALYTICS_EVENTS.PRODUCTO_CREADO_EXITOSO,
  CLIENTE_CREADO_EXITOSO: ANALYTICS_EVENTS.CLIENTE_CREADO_EXITOSO,
  IMPORTACION_COMPLETADA: ANALYTICS_EVENTS.IMPORTACION_COMPLETADA,
  REGISTRO_USUARIO_COMPLETADO: ANALYTICS_EVENTS.REGISTRO_USUARIO_COMPLETADO,
} as const

export type EventoPosthogKpi = (typeof EVENTOS_POSTHOG_KPI)[keyof typeof EVENTOS_POSTHOG_KPI]

export const EVENTOS_POSTHOG_KPI_LISTA = [
  EVENTOS_POSTHOG_KPI.VENTA_COMPLETADA,
  EVENTOS_POSTHOG_KPI.PRODUCTO_CREADO_EXITOSO,
  EVENTOS_POSTHOG_KPI.CLIENTE_CREADO_EXITOSO,
  EVENTOS_POSTHOG_KPI.IMPORTACION_COMPLETADA,
  EVENTOS_POSTHOG_KPI.REGISTRO_USUARIO_COMPLETADO,
] as const
