import type { IdPermiso, PermisoCatalogo } from './tiposRolesPermisos';

export const CATALOGO_PERMISOS: PermisoCatalogo[] = [
  {
    id: 'ventas.comprobantes.ver',
    nombre: 'Ver comprobantes',
    descripcion: 'Acceder a la lista y detalle de comprobantes.',
    modulo: 'ventas',
    rutas: ['/comprobantes'],
  },
  {
    id: 'ventas.comprobantes.emitir',
    nombre: 'Emitir comprobantes',
    descripcion: 'Crear comprobantes desde emision o POS.',
    modulo: 'ventas',
    rutas: ['/comprobantes/emision', '/comprobantes/nuevo', '/comprobantes/pos'],
  },
  {
    id: 'ventas.comprobantes.imprimir',
    nombre: 'Imprimir comprobantes',
    descripcion: 'Imprimir comprobantes generados desde emision tradicional.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.comprobantes.borradores.ver',
    nombre: 'Ver borradores de comprobantes',
    descripcion: 'Acceder a la lista de borradores.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.comprobantes.borradores.duplicar',
    nombre: 'Duplicar borradores',
    descripcion: 'Duplicar un borrador existente.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.comprobantes.borradores.eliminar',
    nombre: 'Eliminar borradores',
    descripcion: 'Eliminar borradores de comprobantes.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.pos.ver',
    nombre: 'Ver punto de venta',
    descripcion: 'Acceder a las pantallas de POS.',
    modulo: 'ventas',
    rutas: ['/punto-venta', '/punto-venta/nueva-venta'],
  },
  {
    id: 'ventas.pos.vender',
    nombre: 'Registrar ventas POS',
    descripcion: 'Crear ventas y emitir comprobantes desde POS.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.pos.imprimir',
    nombre: 'Imprimir comprobantes POS',
    descripcion: 'Imprimir comprobantes desde POS.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.documentos.crear',
    nombre: 'Crear documentos comerciales',
    descripcion: 'Crear cotizaciones, notas de venta u órdenes de venta.',
    modulo: 'ventas',
    rutas: ['/documentos-comerciales', '/documentos-comerciales/nuevo/:tipo'],
  },
  {
    id: 'ventas.documentos.ver',
    nombre: 'Ver documentos comerciales',
    descripcion: 'Acceder al listado de documentos comerciales.',
    modulo: 'ventas',
    rutas: ['/documentos-comerciales'],
  },
  {
    id: 'ventas.documentos.editar',
    nombre: 'Editar documentos comerciales',
    descripcion: 'Editar documentos comerciales existentes.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.documentos.eliminar',
    nombre: 'Eliminar documentos comerciales',
    descripcion: 'Eliminar documentos comerciales.',
    modulo: 'ventas',
  },
  {
    id: 'ventas.gre.ver',
    nombre: 'Ver guías de remisión',
    descripcion: 'Acceder al listado y detalle de guías de remisión electrónica.',
    modulo: 'ventas',
    rutas: ['/guias-remision'],
  },
  {
    id: 'ventas.gre.emitir',
    nombre: 'Crear y emitir GRE',
    descripcion: 'Crear, editar y emitir guías de remisión electrónica (remitente y transportista).',
    modulo: 'ventas',
    rutas: ['/guias-remision/nuevo/:tipoParam', '/guias-remision/editar/:id'],
  },
  {
    id: 'clientes.ver',
    nombre: 'Ver clientes',
    descripcion: 'Acceder al listado y detalle de clientes.',
    modulo: 'clientes',
    rutas: ['/clientes', '/clientes/:clienteId/:clienteName/historial'],
  },
  {
    id: 'clientes.crear',
    nombre: 'Crear clientes',
    descripcion: 'Registrar nuevos clientes.',
    modulo: 'clientes',
  },
  {
    id: 'clientes.editar',
    nombre: 'Editar clientes',
    descripcion: 'Editar informacion de clientes.',
    modulo: 'clientes',
  },
  {
    id: 'clientes.eliminar',
    nombre: 'Eliminar clientes',
    descripcion: 'Eliminar clientes.',
    modulo: 'clientes',
  },
  {
    id: 'clientes.importar',
    nombre: 'Importar clientes',
    descripcion: 'Importar clientes en lote.',
    modulo: 'clientes',
    rutas: ['/importar-clientes'],
  },
  {
    id: 'cobranzas.ver',
    nombre: 'Ver cobranzas',
    descripcion: 'Acceder al modulo de cobranzas.',
    modulo: 'cobranzas',
    rutas: ['/cobranzas'],
  },
  {
    id: 'cobranzas.registrar',
    nombre: 'Registrar cobranzas',
    descripcion: 'Registrar pagos y cobranzas.',
    modulo: 'cobranzas',
  },
  {
    id: 'caja.ver',
    nombre: 'Ver caja',
    descripcion: 'Acceder al modulo de caja.',
    modulo: 'caja',
    rutas: ['/control-caja', '/caja/sesiones'],
  },
  {
    id: 'caja.abrir',
    nombre: 'Abrir caja',
    descripcion: 'Registrar apertura de caja.',
    modulo: 'caja',
  },
  {
    id: 'caja.cerrar',
    nombre: 'Cerrar caja',
    descripcion: 'Registrar cierre de caja.',
    modulo: 'caja',
  },
  {
    id: 'caja.movimientos.registrar',
    nombre: 'Registrar movimientos de caja',
    descripcion: 'Registrar ingresos y egresos de caja.',
    modulo: 'caja',
  },
  {
    id: 'inventario.ver',
    nombre: 'Ver inventario',
    descripcion: 'Acceder al modulo de inventario.',
    modulo: 'inventario',
    rutas: ['/inventario'],
  },
  {
    id: 'inventario.ajustar',
    nombre: 'Ajustar inventario',
    descripcion: 'Registrar ajustes de stock.',
    modulo: 'inventario',
  },
  {
    id: 'inventario.transferir',
    nombre: 'Transferir inventario',
    descripcion: 'Registrar transferencias de stock.',
    modulo: 'inventario',
  },
  {
    id: 'inventario.actualizacion_masiva',
    nombre: 'Actualizacion masiva de inventario',
    descripcion: 'Aplicar actualizaciones masivas de stock.',
    modulo: 'inventario',
  },
  {
    id: 'catalogo.ver',
    nombre: 'Ver catalogo',
    descripcion: 'Acceder al catalogo de productos.',
    modulo: 'catalogo',
    rutas: ['/catalogo'],
  },
  {
    id: 'catalogo.crear',
    nombre: 'Crear productos',
    descripcion: 'Registrar productos en el catalogo.',
    modulo: 'catalogo',
  },
  {
    id: 'catalogo.editar',
    nombre: 'Editar productos',
    descripcion: 'Editar productos del catalogo.',
    modulo: 'catalogo',
  },
  {
    id: 'catalogo.eliminar',
    nombre: 'Eliminar productos',
    descripcion: 'Eliminar productos del catalogo.',
    modulo: 'catalogo',
  },
  {
    id: 'precios.ver',
    nombre: 'Ver precios',
    descripcion: 'Acceder a la lista de precios.',
    modulo: 'precios',
    rutas: ['/lista-precios'],
  },
  {
    id: 'precios.editar',
    nombre: 'Editar precios',
    descripcion: 'Editar listas o reglas de precios.',
    modulo: 'precios',
  },
  {
    id: 'indicadores.ver',
    nombre: 'Ver indicadores',
    descripcion: 'Acceder a indicadores del negocio.',
    modulo: 'indicadores',
    rutas: ['/indicadores'],
  },
  {
    id: 'config.panel.ver',
    nombre: 'Ver panel de configuracion',
    descripcion: 'Acceder al panel principal de configuracion.',
    modulo: 'configuracion',
    rutas: ['/configuracion'],
  },
  {
    id: 'config.empresa.ver',
    nombre: 'Ver configuracion de empresa',
    descripcion: 'Acceder a los datos de empresa.',
    modulo: 'configuracion',
    rutas: ['/configuracion/empresa'],
  },
  {
    id: 'config.empresa.editar',
    nombre: 'Editar configuracion de empresa',
    descripcion: 'Editar los datos de empresa.',
    modulo: 'configuracion',
  },
  {
    id: 'config.establecimientos.gestionar',
    nombre: 'Gestionar establecimientos',
    descripcion: 'Crear, editar o eliminar establecimientos.',
    modulo: 'configuracion',
    rutas: ['/configuracion/establecimientos'],
  },
  {
    id: 'config.almacenes.gestionar',
    nombre: 'Gestionar almacenes',
    descripcion: 'Crear, editar o eliminar almacenes.',
    modulo: 'configuracion',
    rutas: ['/configuracion/almacenes'],
  },
  {
    id: 'config.series.gestionar',
    nombre: 'Gestionar series',
    descripcion: 'Crear, editar o eliminar series.',
    modulo: 'configuracion',
    rutas: ['/configuracion/series'],
  },
  {
    id: 'config.series.correlativo.ajustar',
    nombre: 'Ajustar correlativo de series',
    descripcion: 'Ajustar el correlativo de series.',
    modulo: 'configuracion',
  },
  {
    id: 'config.negocio.gestionar',
    nombre: 'Gestionar configuracion de negocio',
    descripcion: 'Actualizar medios de pago, impuestos, unidades y preferencias.',
    modulo: 'configuracion',
    rutas: ['/configuracion/negocio'],
  },
  {
    id: 'config.diseno_comprobante.gestionar',
    nombre: 'Gestionar diseno de comprobantes',
    descripcion: 'Configurar el diseno de comprobantes.',
    modulo: 'configuracion',
    rutas: ['/configuracion/diseno'],
  },
  {
    id: 'config.diseno_comprobante.importar_exportar',
    nombre: 'Importar y exportar diseno de comprobantes',
    descripcion: 'Importar o exportar configuraciones de diseno.',
    modulo: 'configuracion',
  },
  {
    id: 'config.cajas.gestionar',
    nombre: 'Gestionar cajas',
    descripcion: 'Crear, editar o eliminar cajas.',
    modulo: 'configuracion',
    rutas: ['/configuracion/cajas', '/configuracion/cajas/new', '/configuracion/cajas/:id'],
  },
  {
    id: 'config.usuarios.gestionar',
    nombre: 'Gestionar usuarios',
    descripcion: 'Crear, editar o eliminar usuarios.',
    modulo: 'configuracion',
    rutas: ['/configuracion/usuarios'],
  },
  {
    id: 'config.usuarios.accesos.gestionar',
    nombre: 'Gestionar accesos de usuarios',
    descripcion: 'Gestionar asignaciones y roles de usuarios.',
    modulo: 'configuracion',
  },
  {
    id: 'config.usuarios.reset_password',
    nombre: 'Restablecer credenciales',
    descripcion: 'Restablecer credenciales sin exponer contrasenas.',
    modulo: 'configuracion',
  },
  {
    id: 'config.conexion-sunat.gestionar',
    nombre: 'Gestionar conexión SUNAT',
    descripcion: 'Configurar credenciales SOL y OAuth 2.0 para servicios electrónicos SUNAT.',
    modulo: 'configuracion',
    rutas: ['/configuracion/conexion-sunat'],
  },
  {
    id: 'config.transporte.gestionar',
    nombre: 'Gestionar configuración de transporte',
    descripcion: 'Gestionar datos del transportista, conductores y vehículos para guías de remisión.',
    modulo: 'configuracion',
    rutas: ['/configuracion/transporte'],
  },
  {
    id: 'notificaciones.ver',
    nombre: 'Ver notificaciones',
    descripcion: 'Acceder al centro de notificaciones.',
    modulo: 'notificaciones',
    rutas: ['/notificaciones'],
  },
  {
    id: 'compras.ordenes.ver',
    nombre: 'Ver órdenes de compra',
    descripcion: 'Acceder al listado y detalle de órdenes de compra.',
    modulo: 'compras',
    rutas: ['/compras'],
  },
  {
    id: 'compras.ordenes.crear',
    nombre: 'Crear órdenes de compra',
    descripcion: 'Registrar nuevas órdenes de compra.',
    modulo: 'compras',
  },
  {
    id: 'compras.ordenes.editar',
    nombre: 'Editar órdenes de compra',
    descripcion: 'Editar órdenes de compra en borrador.',
    modulo: 'compras',
  },
  {
    id: 'compras.ordenes.aprobar',
    nombre: 'Aprobar órdenes de compra',
    descripcion: 'Aprobar o rechazar órdenes de compra pendientes.',
    modulo: 'compras',
  },
  {
    id: 'compras.ordenes.anular',
    nombre: 'Anular órdenes de compra',
    descripcion: 'Anular órdenes de compra registradas.',
    modulo: 'compras',
  },
  {
    id: 'compras.comprobantes.ver',
    nombre: 'Ver comprobantes de compra',
    descripcion: 'Acceder al listado y detalle de comprobantes de compra.',
    modulo: 'compras',
  },
  {
    id: 'compras.comprobantes.registrar',
    nombre: 'Registrar comprobantes de compra',
    descripcion: 'Registrar comprobantes emitidos por proveedores.',
    modulo: 'compras',
  },
  {
    id: 'compras.comprobantes.anular',
    nombre: 'Anular comprobantes de compra',
    descripcion: 'Anular comprobantes de compra registrados.',
    modulo: 'compras',
  },
  {
    id: 'compras.cuentas_por_pagar.ver',
    nombre: 'Ver cuentas por pagar',
    descripcion: 'Acceder al listado de cuentas por pagar a proveedores.',
    modulo: 'compras',
  },
  {
    id: 'compras.pagos.ver',
    nombre: 'Ver pagos a proveedores',
    descripcion: 'Acceder al historial de pagos a proveedores.',
    modulo: 'compras',
  },
  {
    id: 'compras.pagos.registrar',
    nombre: 'Registrar pagos a proveedores',
    descripcion: 'Registrar pagos a cuentas por pagar.',
    modulo: 'compras',
  },
  {
    id: 'compras.pagos.anular',
    nombre: 'Anular pagos a proveedores',
    descripcion: 'Anular pagos registrados a proveedores.',
    modulo: 'compras',
  },
];

export const MAPA_PERMISOS_POR_ID: Record<IdPermiso, PermisoCatalogo> =
  CATALOGO_PERMISOS.reduce<Record<IdPermiso, PermisoCatalogo>>((acc, permiso) => {
    acc[permiso.id] = permiso;
    return acc;
  }, {});
